git:
  depth: 5

stages:
  - Test

jobs:
  include:
    - stage: Test
      env:
        - Test: dockerfile_lint
      language: node_js
      node_js:
        - "8"
      script:
        - npx --cache .npx dockerfile_lint
      cache:
        directories:
          - .npx

    - stage: Test
      env:
        - Test: Build Docker image
      language: generic
      arch: amd64
      script:
        - docker build -t peterdavehello-shellcheck-test .
        - docker run --rm peterdavehello-shellcheck-test shellcheck --version
      services:
        - docker

    - stage: Test
      env:
        - Test: Build ARM64 Docker image
      language: generic
      arch: arm64
      script:
        - docker build -t peterdavehello-shellcheck-test .
        - docker run --rm -w /tmp peterdavehello-shellcheck-test shellcheck --version
      services:
        - docker
